# Generated by Django 6.0.5 on 2026-05-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablecard',
            name='class_names',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
