# Generated by Django 6.0.5 on 2026-05-20 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetablecard_class_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_covered', models.BooleanField(default=None, null=True)),
                ('is_replaced', models.BooleanField(default=False)),
                ('replacement_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablecard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_records', to='timetable.teacher')),
            ],
            options={
                'unique_together': {('card', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='timetable.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ReportDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('deadline', models.DateField()),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.teacher')),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
